In [1]:
import pandas as pd
import numpy as np

In [2]:
x = 10
y = 3.14
my_list = {1,2,'sadman'}
print(my_list)

{'sadman', 1, 2}


In [3]:
name = 'sadman'
name1 = [1,2,3]
name2 = {1,2,3,4}
name3 = {"sadman":"1"}
print(type(name))
print(type(name1))
print(type(name2))
print(type(name3))

<class 'str'>
<class 'list'>
<class 'set'>
<class 'dict'>


In [21]:
arr = np.array([1,2,3,4,5])
numbersandwords = np.array([12,234,444,33,67,8,9,"sadman","uddin","sahal","irfan"])
print("numbers:",numbersandwords)
print(arr)
print(arr[0])
print(arr[4])
print(arr[1:4])
print(arr[-3])
print(numbersandwords[8])
print(numbersandwords[2:9])
print(numbersandwords[:-3])


numbers: ['12' '234' '444' '33' '67' '8' '9' 'sadman' 'uddin' 'sahal' 'irfan']
[1 2 3 4 5]
1
5
[2 3 4]
3
uddin
['444' '33' '67' '8' '9' 'sadman' 'uddin']
['12' '234' '444' '33' '67' '8' '9' 'sadman']


In [26]:
arr = np.array([1,2,3,4,5,6])
new_arr = arr*2
print(new_arr)
print(np.sum(arr))
print(np.mean(arr))

[ 2  4  6  8 10 12]
21
3.5


In [29]:
df = pd.read_csv("/Users/mohammedsadmanuddin/data analysis/Intro to numpy and pandas/DPA 01 - Intro Data copy.csv")
df.describe()

,X1,X2
count,1500.000000,1500.000000
mean,-0.379401,2.141568
std,5.215288,6.308511
min,-10.503508,-9.498748
25%,-6.400126,-5.909959
50%,0.676300,5.709203
75%,4.620075,6.934017
max,9.370845,9.871754


In [30]:
new_df = df[df['X1']>5]
new_df

,X1,X2
7,6.516789,6.649863
8,5.133780,5.525237
10,6.358693,6.532480
14,5.285473,7.894073
15,5.474934,4.547032
...,...,...
1486,5.346436,8.405742
1491,5.645917,6.831037
1492,6.079862,7.543592
1494,5.970088,7.352508


In [33]:
dic = {'name':["sadman","sahal","irfan"],'marks':[12,13,44]}
df1=pd.DataFrame(dic)
print(df1)
df1.to_csv('friend')
df1.to_csv('friend_falseindex',index=False)

     name  marks
0  sadman     12
1   sahal     13
2   irfan     44


In [34]:
df1.index = [1,2,3]
df1

,name,marks
1,sadman,12
2,sahal,13
3,irfan,44


In [36]:
series=pd.Series(np.random.rand(10))
series

0    0.071446
1    0.763270
2    0.684731
3    0.204728
4    0.015297
5    0.006207
6    0.139038
7    0.027572
8    0.606972
9    0.375383
dtype: float64

In [41]:
newdataframe = pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
print(newdataframe)
newdataframe.dtypes

            0         1         2         3         4
0    0.766669  0.445942  0.338061  0.840278  0.408591
1    0.123617  0.873513  0.223729  0.404381  0.849085
2    0.694348  0.070547  0.404623  0.534354  0.973052
3    0.659649  0.992704  0.398266  0.529580  0.379230
4    0.617048  0.787518  0.746466  0.942100  0.839207
..        ...       ...       ...       ...       ...
329  0.818969  0.389102  0.799967  0.044341  0.829251
330  0.288639  0.282519  0.182654  0.103338  0.394138
331  0.601129  0.532840  0.663493  0.818582  0.040523
332  0.563606  0.340470  0.736017  0.848506  0.927195
333  0.247036  0.664228  0.615541  0.502843  0.738125

[334 rows x 5 columns]


0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [42]:
newdataframe.to_numpy()

array([[0.76666881, 0.445942  , 0.33806118, 0.84027786, 0.40859097],
       [0.12361699, 0.87351297, 0.22372855, 0.40438061, 0.84908455],
       [0.69434756, 0.07054746, 0.40462269, 0.53435422, 0.97305204],
       ...,
       [0.60112855, 0.53284031, 0.66349292, 0.8185819 , 0.04052291],
       [0.5636064 , 0.34047013, 0.73601716, 0.84850558, 0.92719452],
       [0.24703596, 0.66422828, 0.61554068, 0.50284299, 0.73812494]])

In [43]:
#transpose
print(newdataframe.T)

        0         1         2         3         4         5         6    \
0  0.766669  0.123617  0.694348  0.659649  0.617048  0.539439  0.318318   
1  0.445942  0.873513  0.070547  0.992704  0.787518  0.420748  0.134548   
2  0.338061  0.223729  0.404623  0.398266  0.746466  0.953517  0.134154   
3  0.840278  0.404381  0.534354  0.529580  0.942100  0.039339  0.237278   
4  0.408591  0.849085  0.973052  0.379230  0.839207  0.248406  0.257371   

        7         8         9    ...       324       325       326       327  \
0  0.372461  0.733212  0.324553  ...  0.261459  0.245551  0.473141  0.675100   
1  0.201094  0.557280  0.861071  ...  0.066057  0.058136  0.909100  0.610416   
2  0.072796  0.790876  0.532446  ...  0.511315  0.029319  0.044332  0.666865   
3  0.939320  0.537680  0.395491  ...  0.774422  0.949461  0.637822  0.790283   
4  0.075309  0.600937  0.923113  ...  0.549503  0.956453  0.207612  0.287164   

        328       329       330       331       332       333  
0  0

In [56]:
print(newdataframe.sort_index(axis=0).head(10))

          0         1         2         3         4
0  0.766669  0.445942  0.338061  0.840278  0.408591
1  0.123617  0.873513  0.223729  0.404381  0.849085
2  0.694348  0.070547  0.404623  0.534354  0.973052
3  0.659649  0.992704  0.398266  0.529580  0.379230
4  0.617048  0.787518  0.746466  0.942100  0.839207
5  0.539439  0.420748  0.953517  0.039339  0.248406
6  0.318318  0.134548  0.134154  0.237278  0.257371
7  0.372461  0.201094  0.072796  0.939320  0.075309
8  0.733212  0.557280  0.790876  0.537680  0.600937
9  0.324553  0.861071  0.532446  0.395491  0.923113


In [ ]:
print(newdataframe[0])

0      0.766669
1      0.123617
2      0.694348
3      0.659649
4      0.617048
         ...   
329    0.818969
330    0.288639
331    0.601129
332    0.563606
333    0.247036
Name: 0, Length: 334, dtype: float64


In [51]:
print(newdataframe.loc[0:3])

          0         1         2         3         4
0  0.766669  0.445942  0.338061  0.840278  0.408591
1  0.123617  0.873513  0.223729  0.404381  0.849085
2  0.694348  0.070547  0.404623  0.534354  0.973052
3  0.659649  0.992704  0.398266  0.529580  0.379230


In [58]:
print(newdataframe.iloc[0:5])

          0         1         2         3         4
0  0.766669  0.445942  0.338061  0.840278  0.408591
1  0.123617  0.873513  0.223729  0.404381  0.849085
2  0.694348  0.070547  0.404623  0.534354  0.973052
3  0.659649  0.992704  0.398266  0.529580  0.379230
4  0.617048  0.787518  0.746466  0.942100  0.839207


In [69]:
newdfX = newdataframe
newdfX[0][1] = '0.574628'
newdfX

,0,1,2,3,4
0,0.766669,0.445942,0.338061,0.840278,0.408591
1,0.574628,0.873513,0.574628,0.574628,0.849085
2,0.694348,0.070547,0.404623,0.534354,0.973052
3,0.659649,0.992704,0.398266,0.52958,0.379230
4,0.617048,0.787518,0.746466,0.9421,0.839207
...,...,...,...,...,...
329,0.818969,0.389102,0.799967,0.044341,0.829251
330,0.288639,0.282519,0.182654,0.103338,0.394138
331,0.601129,0.532840,0.663493,0.818582,0.040523
332,0.563606,0.340470,0.736017,0.848506,0.927195


In [70]:
newdataframe

,0,1,2,3,4
0,0.766669,0.445942,0.338061,0.840278,0.408591
1,0.574628,0.873513,0.574628,0.574628,0.849085
2,0.694348,0.070547,0.404623,0.534354,0.973052
3,0.659649,0.992704,0.398266,0.52958,0.379230
4,0.617048,0.787518,0.746466,0.9421,0.839207
...,...,...,...,...,...
329,0.818969,0.389102,0.799967,0.044341,0.829251
330,0.288639,0.282519,0.182654,0.103338,0.394138
331,0.601129,0.532840,0.663493,0.818582,0.040523
332,0.563606,0.340470,0.736017,0.848506,0.927195


In [ ]:
newdataframe.loc[[2,3],[1,4]]

,1,4
2,0.070547,0.973052
3,0.992704,0.379230


In [75]:
newdataframe.loc[:,[2,4]]

,2,4
0,0.338061,0.408591
1,0.574628,0.849085
2,0.404623,0.973052
3,0.398266,0.379230
4,0.746466,0.839207
...,...,...
329,0.799967,0.829251
330,0.182654,0.394138
331,0.663493,0.040523
332,0.736017,0.927195


In [76]:
newdataframe.loc[[2,3],:]

,0,1,2,3,4
2,0.694348,0.070547,0.404623,0.534354,0.973052
3,0.659649,0.992704,0.398266,0.52958,0.379230


In [79]:
newdataframe.columns = ["A","B","C","D","E"]
newdataframe

,A,B,C,D,E
0,0.766669,0.445942,0.338061,0.840278,0.408591
1,0.574628,0.873513,0.574628,0.574628,0.849085
2,0.694348,0.070547,0.404623,0.534354,0.973052
3,0.659649,0.992704,0.398266,0.52958,0.379230
4,0.617048,0.787518,0.746466,0.9421,0.839207
...,...,...,...,...,...
329,0.818969,0.389102,0.799967,0.044341,0.829251
330,0.288639,0.282519,0.182654,0.103338,0.394138
331,0.601129,0.532840,0.663493,0.818582,0.040523
332,0.563606,0.340470,0.736017,0.848506,0.927195


In [90]:
newdataframe = newdataframe.apply(pd.to_numeric)

In [91]:
newdataframe.loc[newdataframe["C"]<0.4]

,A,B,C,D,E
0,0.766669,0.445942,0.338061,0.840278,0.408591
3,0.659649,0.992704,0.398266,0.529580,0.379230
6,0.318318,0.134548,0.134154,0.237278,0.257371
7,0.372461,0.201094,0.072796,0.939320,0.075309
13,0.693471,0.691458,0.236873,0.506796,0.261664
...,...,...,...,...,...
321,0.648917,0.284623,0.019714,0.807014,0.040977
323,0.465810,0.712484,0.129434,0.339445,0.182263
325,0.245551,0.058136,0.029319,0.949461,0.956453
326,0.473141,0.909100,0.044332,0.637822,0.207612


In [92]:
newdataframe.loc[(newdataframe["C"] < 0.4) & (newdataframe['B'])]

,A,B,C,D,E
0,0.766669,0.445942,0.338061,0.840278,0.408591
3,0.659649,0.992704,0.398266,0.529580,0.379230
6,0.318318,0.134548,0.134154,0.237278,0.257371
7,0.372461,0.201094,0.072796,0.939320,0.075309
13,0.693471,0.691458,0.236873,0.506796,0.261664
...,...,...,...,...,...
321,0.648917,0.284623,0.019714,0.807014,0.040977
323,0.465810,0.712484,0.129434,0.339445,0.182263
325,0.245551,0.058136,0.029319,0.949461,0.956453
326,0.473141,0.909100,0.044332,0.637822,0.207612


In [97]:
newdataframe

,A,B,C,D,E
0,0.766669,0.445942,0.338061,0.840278,0.408591
1,0.574628,0.873513,0.574628,0.574628,0.849085
2,0.694348,0.070547,0.404623,0.534354,0.973052
3,0.659649,0.992704,0.398266,0.529580,0.379230
4,0.617048,0.787518,0.746466,0.942100,0.839207
...,...,...,...,...,...
329,0.818969,0.389102,0.799967,0.044341,0.829251
330,0.288639,0.282519,0.182654,0.103338,0.394138
331,0.601129,0.532840,0.663493,0.818582,0.040523
332,0.563606,0.340470,0.736017,0.848506,0.927195


In [ ]:
newdataframe.loc[2,"A"]

np.float64(0.6943475564535463)

In [96]:
newdataframe.iloc[2,4]

np.float64(0.9730520369136932)

In [100]:
pokemon = pd.read_csv("/Users/mohammedsadmanuddin/data analysis/data ingestion and selection/Pokemon.csv",sep=";",index_col=0)
pokemon.head()

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False


In [101]:
type(pokemon)

pandas.core.frame.DataFrame

In [102]:
type(pokemon['Name'])

pandas.core.series.Series

In [103]:
pokemon.Attack

#
1       49
2       62
3       82
3      100
4       52
      ... 
719    100
719    160
720    110
720    160
721    110
Name: Attack, Length: 800, dtype: int64

In [104]:
pokemon['Defense']

#
1       49
2       63
3       83
3      123
4       43
      ... 
719    150
719    110
720     60
720     60
721    120
Name: Defense, Length: 800, dtype: int64

In [106]:
pokemon[["Attack","Defense","HP"]]

,Attack,Defense,HP
#,,,
1,49,49,45
2,62,63,60
3,82,83,80
3,100,123,80
4,52,43,39
...,...,...,...
719,100,150,50
719,160,110,50
720,110,60,80


In [110]:
pokemon[2:6]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False


In [116]:
pokemon.loc[4,"Attack"]

np.int64(52)

In [114]:
pokemon.iloc[4,5]

np.int64(52)

In [122]:
pokemon.iloc[:10,1:6]

,Type 1,Type 2,Total,HP,Attack
#,,,,,
1,Grass,Poison,318,45,49
2,Grass,Poison,405,60,62
3,Grass,Poison,525,80,82
3,Grass,Poison,625,80,100
4,Fire,NaN,309,39,52
5,Fire,NaN,405,58,64
6,Fire,Flying,534,78,84
6,Fire,Dragon,634,78,130
6,Fire,Flying,634,78,104


In [124]:
pokemon["New"] = False
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,New
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,False
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,False
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,False


In [130]:
pokemon[pokemon["Attack"]<50]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False
12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
678,MeowsticMale,Psychic,NaN,466,74,48,76,83,81,104,6,False
678,MeowsticFemale,Psychic,NaN,466,74,48,76,83,81,104,6,False
684,Swirlix,Fairy,NaN,341,62,48,66,59,57,49,6,False


In [131]:
pokemon[pokemon.Attack<50]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False
12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
678,MeowsticMale,Psychic,NaN,466,74,48,76,83,81,104,6,False
678,MeowsticFemale,Psychic,NaN,466,74,48,76,83,81,104,6,False
684,Swirlix,Fairy,NaN,341,62,48,66,59,57,49,6,False


In [133]:
pokemon.loc[np.logical_and(pokemon["HP"]>50,pokemon["Defense"]<30)]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
39,Jigglypuff,Normal,Fairy,270,115,45,20,45,25,20,1,False
113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
174,Igglybuff,Normal,Fairy,210,90,30,15,40,20,15,2,False
242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
293,Whismur,Normal,NaN,240,64,51,23,51,23,28,3,False
440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False


In [134]:
pokemon.loc[(pokemon["HP"]>50)&(pokemon["Defense"]<30)]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
39,Jigglypuff,Normal,Fairy,270,115,45,20,45,25,20,1,False
113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
174,Igglybuff,Normal,Fairy,210,90,30,15,40,20,15,2,False
242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
293,Whismur,Normal,NaN,240,64,51,23,51,23,28,3,False
440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False


In [135]:
len(pokemon[pokemon["Legendary"]])

65

In [138]:
pokemon.loc[np.logical_and(pokemon["Type 2"]=="Flying",pokemon["Speed"]==60)].loc[83,"Name"]

"Farfetch'd"

In [139]:
df1 = pokemon.loc[:10,:"Attack"]
df1

,Name,Type 1,Type 2,Total,HP,Attack
#,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49
2,Ivysaur,Grass,Poison,405,60,62
3,Venusaur,Grass,Poison,525,80,82
3,VenusaurMega Venusaur,Grass,Poison,625,80,100
4,Charmander,Fire,NaN,309,39,52
5,Charmeleon,Fire,NaN,405,58,64
6,Charizard,Fire,Flying,534,78,84
6,CharizardMega Charizard X,Fire,Dragon,634,78,130
6,CharizardMega Charizard Y,Fire,Flying,634,78,104


In [141]:
df2 = pokemon.loc[:20,:"Sp. Atk"]
df2

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk
#,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65
2,Ivysaur,Grass,Poison,405,60,62,63,80
3,Venusaur,Grass,Poison,525,80,82,83,100
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122
4,Charmander,Fire,NaN,309,39,52,43,60
5,Charmeleon,Fire,NaN,405,58,64,58,80
6,Charizard,Fire,Flying,534,78,84,78,109
6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130
6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159


In [142]:
pd.concat([df1,df2])

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk
#,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,NaN,NaN
2,Ivysaur,Grass,Poison,405,60,62,NaN,NaN
3,Venusaur,Grass,Poison,525,80,82,NaN,NaN
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,NaN,NaN
4,Charmander,Fire,NaN,309,39,52,NaN,NaN
5,Charmeleon,Fire,NaN,405,58,64,NaN,NaN
6,Charizard,Fire,Flying,534,78,84,NaN,NaN
6,CharizardMega Charizard X,Fire,Dragon,634,78,130,NaN,NaN
6,CharizardMega Charizard Y,Fire,Flying,634,78,104,NaN,NaN


In [145]:
df3=pd.concat([df1,df2],axis=0)
df3

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk
#,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,NaN,NaN
2,Ivysaur,Grass,Poison,405,60,62,NaN,NaN
3,Venusaur,Grass,Poison,525,80,82,NaN,NaN
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,NaN,NaN
4,Charmander,Fire,NaN,309,39,52,NaN,NaN
5,Charmeleon,Fire,NaN,405,58,64,NaN,NaN
6,Charizard,Fire,Flying,534,78,84,NaN,NaN
6,CharizardMega Charizard X,Fire,Dragon,634,78,130,NaN,NaN
6,CharizardMega Charizard Y,Fire,Flying,634,78,104,NaN,NaN
